export const metadata = {
  title: "Terms & Conditions | Mittal Catering Ajmer",
  description:
    "Read the Terms & Conditions of Mittal Catering Ajmer regarding website usage, services, orders, payments, and legal policies.",
};

const page = () => {
  return (
    <section className="bg-black text-gray-300">
      <div className="max-w-7xl mx-auto px-4 py-12">
        {/* Page Title */}
        <h1 className="text-3xl md:text-4xl font-bold text-white mb-6">
          Terms & Conditions
        </h1>

        {/* Content */}
        <div className="space-y-6 text-sm leading-relaxed">
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and the rules made thereunder. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediary Guidelines and
            Digital Media Ethics Code) Rules, 2021, which require publishing the
            rules and regulations, privacy policy, and terms of use for access
            or usage of the website https://www.mittalcateringajmer.com/.
          </p>

          <p>
            The website https://www.mittalcateringajmer.com/ (“Website” or
            “Platform”) is owned and operated by Mittal Catering Ajmer, having
            its principal place of business at House No. 1053A, Mittal Bhawan,
            Dhola Bhata Road, near All Saint School, Professors Colony, Dhola
            Bhata Colony, Ajmer, Rajasthan – 305007.
          </p>

          <p>
            By accessing, browsing, or using this Platform in any manner,
            including placing an order or making an enquiry, you agree to be
            bound by these Terms & Conditions along with our Privacy Policy and
            any other policies published on the Website. If you do not agree
            with these terms, please do not use the Platform.
          </p>

          <h2 className="text-white font-semibold">1. User Eligibility</h2>
          <p>
            1.1 The user must be legally capable of entering into a binding
            contract under the laws of India.
          </p>
          <p>
            1.2 By using this Platform, you represent and warrant that you are
            competent to place orders, make payments, and avail our services.
          </p>

          <h2 className="text-white font-semibold">2. Nature of Services</h2>
          <p>
            2.1 Mittal Catering Ajmer provides catering services, bulk food
            orders, event catering, and related food services through offline
            and online modes.
          </p>
          <p>
            2.2 Images of food, menus, or events displayed on the Platform are
            for representational purposes only. Actual presentation may vary
            based on availability, season, or customization.
          </p>
          <p>
            2.3 Service timelines, preparation times, and delivery schedules
            mentioned are estimates and may vary due to operational or external
            factors.
          </p>

          <h2 className="text-white font-semibold">
            3. User Information & Responsibilities
          </h2>
          <p>
            3.1 You agree to provide accurate, complete, and up-to-date
            information while placing orders or submitting enquiries.
          </p>
          <p>
            3.2 You are solely responsible for the correctness of delivery
            details, event details, contact information, and special
            instructions provided by you.
          </p>
          <p>
            3.3 Mittal Catering Ajmer shall not be liable for any loss, delay,
            or inconvenience caused due to incorrect or incomplete information
            provided by the user.
          </p>

          <h2 className="text-white font-semibold">4. Pricing & Payments</h2>
          <p>
            4.1 All prices mentioned on the Platform are in Indian Rupees (INR)
            unless stated otherwise.
          </p>
          <p>
            4.2 Prices, menus, and service charges are subject to change without
            prior notice.
          </p>
          <p>
            4.3 Payments may be accepted through cash, UPI, bank transfer, or
            any other payment mode communicated at the time of order
            confirmation.
          </p>
          <p>
            4.4 We do not store any sensitive financial information such as card
            details or banking credentials on our servers.
          </p>

          <h2 className="text-white font-semibold">
            5. Order Confirmation, Cancellation & Refunds
          </h2>
          <p>
            5.1 Orders or bookings shall be considered confirmed only after
            mutual confirmation and receipt of advance payment, wherever
            applicable.
          </p>
          <p>
            5.2 Cancellation terms may vary based on the nature of service, size
            of order, and preparation stage.
          </p>
          <p>
            5.3 Once food preparation or event arrangements have commenced,
            cancellations may not be permitted and refunds may not be
            applicable.
          </p>
          <p>
            5.4 Mittal Catering Ajmer reserves the right to cancel any order due
            to non-availability of raw materials, operational constraints, or
            unforeseen circumstances. In such cases, any advance payment
            received shall be refunded as per applicable terms.
          </p>

          <h2 className="text-white font-semibold">
            6. Delivery & Service Execution
          </h2>
          <p>
            6.1 Delivery timelines and service execution schedules are
            approximate and may vary due to traffic, weather conditions, venue
            constraints, or force majeure events.
          </p>
          <p>
            6.2 Any delay caused due to third-party logistics providers, venue
            restrictions, or customer-side issues shall not be the
            responsibility of Mittal Catering Ajmer.
          </p>
          <p>
            6.3 Risk associated with food and services passes to the customer
            upon successful delivery or completion of service.
          </p>

          <h2 className="text-white font-semibold">
            7. Food Quality, Allergens & Safety
          </h2>
          <p>
            7.1 We follow standard hygiene and food safety practices during
            preparation and service.
          </p>
          <p>
            7.2 Certain food items may contain allergens such as milk, dairy
            products, nuts, gluten, spices, or other ingredients.
          </p>
          <p>
            7.3 Customers with allergies, dietary restrictions, or specific
            health conditions are advised to inform us in advance and exercise
            discretion while ordering.
          </p>
          <p>
            7.4 Mittal Catering Ajmer shall not be liable for allergic reactions
            unless caused due to proven gross negligence on our part.
          </p>

          <h2 className="text-white font-semibold">
            8. Intellectual Property Rights
          </h2>
          <p>
            8.1 All content available on this Platform, including text, images,
            logos, designs, menus, and brand identifiers, are the intellectual
            property of Mittal Catering Ajmer.
          </p>
          <p>
            8.2 Unauthorized copying, reproduction, modification, distribution,
            or commercial use of any content is strictly prohibited.
          </p>

          <h2 className="text-white font-semibold">9. Prohibited Activities</h2>
          <p>
            Users agree not to use the Platform for any unlawful or fraudulent
            purpose, provide false or misleading information, attempt to damage
            or interfere with the Platform, or violate any applicable laws.
          </p>

          <h2 className="text-white font-semibold">
            10. Limitation of Liability
          </h2>
          <p>
            10.1 Our maximum liability, if any, shall be limited to the amount
            paid by the customer for the specific service or order.
          </p>
          <p>
            10.2 We shall not be liable for any indirect, incidental,
            consequential, or special damages.
          </p>

          <h2 className="text-white font-semibold">11. Force Majeure</h2>
          <p>
            Mittal Catering Ajmer shall not be held liable for failure or delay
            in performance due to events beyond reasonable control, including
            natural disasters, strikes, pandemics, government restrictions,
            technical failures, or acts of God.
          </p>

          <h2 className="text-white font-semibold">12. Third-Party Links</h2>
          <p>
            12.1 The Platform may contain links to third-party websites for
            informational purposes.
          </p>
          <p>
            12.2 We do not endorse or take responsibility for such third-party
            websites.
          </p>

          <h2 className="text-white font-semibold">13. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Mittal Catering Ajmer, its
            owners, staff, and associates from any claims arising out of misuse
            of the Platform.
          </p>

          <h2 className="text-white font-semibold">
            14. Modifications to Terms
          </h2>
          <p>
            14.1 We reserve the right to modify these Terms & Conditions at any
            time.
          </p>
          <p>
            14.2 Continued use of the Platform shall constitute acceptance of
            the revised Terms.
          </p>

          <h2 className="text-white font-semibold">
            15. Governing Law & Jurisdiction
          </h2>
          <p>
            15.1 These Terms & Conditions shall be governed by the laws of
            India.
          </p>
          <p>
            15.2 All disputes shall be subject to the exclusive jurisdiction of
            the courts of Ajmer, Rajasthan.
          </p>

          <h2 className="text-white font-semibold">16. Contact Information</h2>
          <p>
            For any queries, complaints, or legal communications, you may
            contact us at:
          </p>
          <p>Email: info@mittalcateringajmer.com</p>
          <p>
            Address: House No. 1053A, Mittal Bhawan, Dhola Bhata Road, near All
            Saint School, Professors Colony, Dhola Bhata Colony, Ajmer,
            Rajasthan – 305007
          </p>
        </div>
      </div>
    </section>
  );
};

export default page;
